### PR TITLE
#184581345 User can list all items

### PR DESCRIPTION
**Pull request by Martha-Iradukunda**
… #184581345

#### What does this PR do?
 * To implement the task of allowing a user to list all items. 
#### Description of Task to be completed?
* It will allow a seller to retrieve a list of all items in their collection, and a buyer to retrieve a list of all items on the available list of products. This should allow for a high level inspection.
* GET/products Retrieve all products
* GET/product  Retrieve all products by seller
#### How should this be manually tested?
* To manually test this, the user should send a get request to retrieve all of a seller's items and confirm that the response is a json object containing a status code, message, and items as an array. If there are no items, then an empty array should be returned as the value of the items property. If the request body fails any validation checks or the token is not of the role seller, then the json object should contain an status property with the appropriate 4XX code, and an error property with the correct error message.

#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker/Trello stories?
* [#184581345](https://www.pivotaltracker.com/n/projects/2632830/stories/184581345)

#### Screenshots (if appropriate)
*  
Screenshot from 2023-03-16 19-54-16
*  
Screenshot from 2023-03-17 12-50-32

#### Questions:
* 1. What type of request is needed to retrieve all of a seller's items?
* 2. What should the response contain if no items are found?

### CODE REVIEW

**Comment by Zeden12** [comment]
fix the conflicts with the tests and you're ready to move

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]

**Review by nshutijonathan — APPROVED** [review]

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]
Nice!

**Pull request merged**
