### PR TITLE
#184699564 verify email after update profile

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
The PR is for sending email if you change the email to verify you new email

#### Description of Task to be completed?
the PR has the following endPoints
- PATCH /users/profile

here the user must be logged in so that they get his/her data in the JWT token
- for PATCH it returns `token` so that in case the email changes the user get other token
```
{
  "token": "string",
  "email_token": "string",
  "verified": "string",
  "username": "string",
  "email": "string",
  "gender": "string",
  "role": "string"
}
```
#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
- uses `Jwt` library
- Sendgrid helps to send email

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/story/show/184699564

#### Screenshots (if appropriate)
Screen Shot 2023-03-15 at 01 10 59

#### Questions:
n/a

### CODE REVIEW

**Review by INValentin — APPROVED** [review]
LTGM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]

**Review by UmuhireJessie — APPROVED** [review]
Well done!

**Pull request merged**
