### PR TITLE
bg: fix google login

### PR DESCRIPTION
**Pull request by INValentin**
#### What does this PR do?

This is a fix to google login to redirect to the actual frontend when a user login with google.

#### Description of Task to be completed?

This is a fix to google login to redirect to the actual frontend when a user login with google.

#### Any background context you want to provide?

This needs an `env` variable `FRONTEND_URL` which points to the react app.

#### What are the relevant pivotal tracker/Trello stories?
n/a
#### Screenshots (if appropriate)
n/a
#### Questions:
n/a

### CODE REVIEW

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Add `REACT_CLIENT_REDIRECT_URL ` in `.env.example` OR use existing `FRONTEND_URL` which points to frontend URL

**Review by edwinnambaje — APPROVED** [review]

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Remove `.env` in committed files

**Review by UmuhireJessie — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Please remove .env file

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
