### PR TITLE
#184686439 BUG(Fix Readme)

### PR DESCRIPTION
**Pull request by INValentin**
#### Description of Task to be completed?
This is to fix the readme adding the registration guide .

#### How should this be manually tested?
Just read the readme
#### What are the relevant pivotal tracker/Trello stories?
[https://www.pivotaltracker.com/n/projects/2632830/stories/184686439](url)
#### Screenshots (if appropriate)
n/a
#### Questions:
n/a

### CODE REVIEW

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
Hey  
Please add an ID to your PR ,you can get it from the PT board

**Comment by INValentin** [comment]
> 

But this is not related to any story, it's an enhancement.

**Comment by nshutijonathan** [comment]
> > 
> 
> But this is not related to any story, it's an enhancement.

`https://www.pivotaltracker.com/story/show/184686439`

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Pull request merged**
