### PR TITLE
ch(deploy base application on render): implement deployment

### PR DESCRIPTION
**Pull request by bencyubahiro77**
-implement deploying base application on render

[Finished #184581325]

#### What does this PR do?
Deploy base application on render

#### Description of Task to be completed?
GIVEN application URLs
WHEN user navigates to provided URLs in browser
THEN user should access the live application

added the following .env.example
-SWAGGER_SERVER
#### How should this be manually tested?
- in your browser add `https://e-comm-team-brogrammers-bn-staging.onrender.com`

#### Any background context you want to provide?
n/a

#### What are the relevant pivotal tracker/Trello stories?
# 184581325 (Deploy base application on render)
https://www.pivotaltracker.com/n/projects/2632830/stories/184581325

#### Questions:
n/a

### CODE REVIEW

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]
Looks good
but remember to add online database in Environment variables

**Comment by bencyubahiro77** [comment]
> Looks good but remember to add online database in Environment variables

it is there in my environment variable on render

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Pull request merged**
