### PR TITLE
 #184581360 adding notifications

### PR DESCRIPTION
**Pull request by Patienceineza**
#### What does this PR do?

This PR id for adding notifications

#### Description of Task to be completed?

this task is composed of making sure that the user gets correct notification according to actions made on products

#### How should this be manually tested?

-first of all clone the repo and  run `npm run migrate:all`
- then login and put token in bearer
- you can check your notifications on `/notifications` with GET method
-  you can delete your notification `/notifications/notificationId` or even clear using `/notifications/clear` with patch  

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184581360

#### Screenshots (if appropriate)
Screenshot 2023-03-30 at 09 36 43
Screenshot 2023-03-29 at 17 55 31

#### Questions:
n/a

### CODE REVIEW

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by Habihirwe — APPROVED** [review]
good

**Review by edwinnambaje — APPROVED** [review]

**Review by bencyubahiro77 — APPROVED** [review]

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Pull request merged**
