### PR TITLE
#184581347 user add item to their wishlist  

### PR DESCRIPTION
**Pull request by Patienceineza**
#### What does this PR do?

This  PR is for users to be able to add  products to their wishlist 

#### Description of Task to be completed?

this task is associated with creating routes for wishlists and controllers to that
-first created middlewares for checking product id validity and other middleware to check if product is not already in wishlist
because you can not wish for product twice
-then test the end points with mocha and chai
- then swaggify the endpoints

#### How should this be manually tested?

-After cloning the repo  run `npm run migrate:all`
-Get id of product you want to add in your wishlist
- Then login and put token in bearer
- use this end point `/wishlist/productId` then POST
- to get all all products in your wishlist use `/wishlist` then use GET

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184581347

#### Screenshots (if appropriate)
Screenshot 2023-03-21 at 12 37 31
Screenshot 2023-03-21 at 12 41 59

#### Questions:
n/a

### CODE REVIEW

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]
Good job!

**Pull request merged**
