### PR TITLE
#184601929 Integrate Coveralls code coverage service

### PR DESCRIPTION
**Pull request by Martha-Iradukunda**
integrate Coveralls code coverage service

### CODE REVIEW

**Comment by Martha-Iradukunda** [comment]
#184581321 I worked on Integrating Coveralls code coverage service which will ensure that we are properly informed just how well our code base is tested ,which in turn provides quality assurance for the product.

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]
Good one

**Review by INValentin — APPROVED** [review]
LGTM

**Pull request closed without merging**
