### PR TITLE
feat(add product) seller add products #184581341

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
The PR is for posting and update the product 

#### Description of Task to be completed?
the PR has the following endPoints
- POST /products/
- PATCH /products/{id}

here the user must be logged in so that they get his/her data in the JWT token
- for POST and PATCH it returns the following
```
{
  "message": "product created | edited",
  "product": {
    "id": "531f60c8-d7e4-4c7e-9316-9d226237b356",
    "images": [
      "http://res.cloudinary.com/dpfueuupz/image/upload/v1678901154/ddhyu8kryfuucpzcis9v.jpg",
      "http://res.cloudinary.com/dpfueuupz/image/upload/v1678901159/iclk1ovdiihr6jgzozuy.png"
    ],
    "name": "nike new",
    "description": "hey you can buy new shoes",
    "quantity": 100,
    "sellerId": "963b5889-a9e6-4b5b-815d-ffc7f5a6975f",
    "exp_date": "2030-03-01T22:00:00.000Z",
    "available": false,
    "price": 250,
    "category": 2,
    "createdAt": "2023-03-15T17:20:57.685Z",
    "updatedAt": "2023-03-15T17:28:08.077Z"
  }
}
```
#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
- uses `Jwt` library
- Cloudinary to upload images

#### What are the relevant pivotal tracker/Trello stories?
- https://www.pivotaltracker.com/story/show/184581341
- https://www.pivotaltracker.com/story/show/184581346

#### Screenshots (if appropriate)
Screen Shot 2023-03-16 at 12 55 36
Screen Shot 2023-03-16 at 12 56 12

#### Questions:
n/a

### CODE REVIEW

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]
Good work bro

**Pull request merged**
