### PR TITLE
184581352 buyer can clear their cart

### PR DESCRIPTION
**Pull request by bencyubahiro77**
#### What does this PR do?
 this PR is for user to reset their cart
#### Description of Task to be completed?
This task the user will be able to reset their cart to zero and their receive a confirmation message

#### How should this be manually tested?

- ``npm run migrate:all.``
- then use this endpoint ``/cart`` with delete to clear the cart

#### Any background context you want to provide?
na

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581352

#### Screenshots (if appropriate)
Screenshot 2023-03-23 at 23 17 10

### CODE REVIEW

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by INValentin — APPROVED** [review]

**Comment by Zeden12** [comment]
rebase and you're good to go

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
