### PR TITLE
#184581328 On successful registration users will receive a JWT

### PR DESCRIPTION
**Pull request by Zeden12**
#### What does this PR do?

Generating token when User Registration Successful

#### Description of Task to be completed?

1. User signup successful
2. generate token to the user after registration

#### How should this be manually tested?

1. clone [e-comm-team-brogrammers-bn](https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn)

2. cd to [ft-signup-token-184581328](https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn/tree/ft-signup-token-184581328)

3. run [npm run migrate:all]  to run seeds and migrations

4. go to postman or thunder clients

5. then create user and post it, actually it will generate token

#### What are the relevant pivotal tracker/Trello stories?

[184581328](https://www.pivotaltracker.com/story/show/184581328)

#### Screenshots (if appropriate)

Screen Shot 2023-03-13 at 18 06 10

### CODE REVIEW

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
Rename your commit message from `Feature(Generating token):On successfu registration user get jwt #184` to `feat(Generating token):On successfu registration user get jwt`

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
Rename your commit message from `Feature(Generating token):On successfu registration user get jwt #184` to `feature(Generating token):On successfu registration user get jwt #184`

**Review by edwinnambaje — CHANGES_REQUESTED** [review]
First solve conflicts and tests on circle ci and then you are good to go

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]

**Review by Patienceineza — APPROVED** [review]
LGTM

**Pull request merged**
