### PR TITLE
#184581320 Integrate HoundCi with badge attached to readme

### PR DESCRIPTION
**Pull request by Zeden12**
What does this PR do?

To configure HoundCi and integrate it with badge attached to readme .

Description of task?

HoundCi will automatically reviews pull requests for style guide violations and other potential issues in the codebase, which will helps to ensure that code adheres to a consistent style and quality across the codebase, which can improve the readability, maintenability, and overall quality of the code.

How should this be manually tested?

1. Clone the [repo](https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn)
2. Change into the directory e-comm-team-brogrammers-bn
3. Checkout branch [ft-houndci-bot-184581320]

Any background context you want to provide?

1. For the success checkup of HoundCi the badge will be green which means no violation of rules in codes and red when there is some violation 

What are the relevant pivotal tracker stories?

[184581320](https://www.pivotaltracker.com/story/show/184581320)

Screenshoots
N/A

### CODE REVIEW

**Review by bencyubahiro77 — APPROVED** [review]

**Review by INValentin — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]
Looks Better

**Review by Patienceineza — APPROVED** [review]
LGTM

**Comment by SimonImanigirimpuhwe** [comment]
@Zeden12 please squash your commits into a single commit

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by edwinnambaje — COMMENTED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Pull request merged**
