### PR TITLE
#184581356 buyer should be able to checkout

### PR DESCRIPTION
**Pull request by INValentin**
#### What does this PR do?

- This PR is to add ability for users to checkout products from their cart, process order, and update inventory.

#### Description of Task to be completed?
GIVEN a post request for checkout 
        - WHEN the requesting user/token is a buyer and the request body is validated
        - THEN:
            - The order should be processed
            - The delivery and payment information should be saved to the buyer's account
            - The inventory should be updated
            - An order confirmation should be sent to the frontend to be displayed to the buyer
#### How should this be manually tested?

- RUN `npm install && npm run migrate:all && npm run start`
- Visit the `/api-docs` endpoint and go to checkout, or use `api client` and access `/checkout` route

#### Any background context you want to provide?
Screenshot 2023-03-24 at 00 39 22

N/A
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581356
#### Screenshots (if appropriate)
Screenshot 2023-03-24 at 00 25 50

#### Questions:
N/A

### CODE REVIEW

**Review by Patienceineza — APPROVED** [review]
LG

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by blackd44 — APPROVED** [review]
LG

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
