### PR TITLE
#184581343 Seller to delete a specific item from their collection

### PR DESCRIPTION
**Pull request by edwinnambaje**
#### What does this PR do?
The PR is for a seller should be able to delete a specific item from their collection

#### Description of Task to be completed?
the PR has the following endPoints
- DELETE delete/products/{id}

here the user must be logged in as a seller so that they get his/her data in the JWT token
- for Delete it returns the following message with the corresponding product that have been deleted
```
{
  "status": 200,
  "message": "Product deleted successfully",
  "item": {
    "id": "04906672-7a61-434e-b3c5-07ab35d0c40d",
    "images": [
      "http://res.cloudinary.com/du0vsc2pt/image/upload/v1679312631/dutnxv74ydhrw6nqmdkl.jpg",
      "http://res.cloudinary.com/du0vsc2pt/image/upload/v1679312635/eemjvmu3hh2jhidr0qom.jpg"
    ],
    "name": "shoe",
    "description": "new nike shoes",
    "quantity": 20,
    "sellerId": "5613282a-6212-4a73-b513-580577cd939d",
    "exp_date": "2023-11-21T22:00:00.000Z",
    "available": true,
    "price": 200,
    "category": 2,
    "createdAt": "2023-03-20T11:43:54.758Z",
    "updatedAt": "2023-03-20T11:43:54.758Z"
  }
}
```
#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in terminal `npm run migrate:all` to setup the database
- run in terminal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
- uses `Jwt` library
- Cloudinary to upload images

#### What are the relevant pivotal tracker/Trello stories?
-https://www.pivotaltracker.com/n/projects/2632830/stories/184581343

#### Screenshots (if appropriate)
Screenshot 2023-03-19 at 22 15 19
Screenshot 2023-03-20 at 13 47 54

#### Questions:
n/a

### CODE REVIEW

**Review by nshutijonathan — COMMENTED** [review]
Update read me  and you are good to go

**Review by INValentin — APPROVED** [review]
LGTM

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]
looks good

**Review by Patienceineza — APPROVED** [review]
LGTM Edwin, good job

**Review by UmuhireJessie — APPROVED** [review]

**Review by Habihirwe — COMMENTED** [review]
well done

**Pull request merged**
