### PR TITLE
#184664900 add uuid as userid

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
- creating account for a new user and validate his/her information
- set the user id to `uuid` format
- testing the user signup routes
- adding documentation of the user signup route

#### Description of Task to be completed?
user must enter the data such as
- username
- email
- password
- gender

then its validate those information
then check if there isn't other account with that email address
and add it in the database 
after return the message that user has been created

endpoints:
- /users/signup

#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
n/a

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184664900

#### Screenshots (if appropriate)
Screen Shot 2023-03-11 at 17 59 35
Screen Shot 2023-03-11 at 17 53 31

#### Questions:
n/a

### CODE REVIEW

**Review by edwinnambaje — APPROVED** [review]
LGTM good work dalton

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by Habihirwe — APPROVED** [review]
great work brother

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
LGTM

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Pull request merged**
