### PR TITLE
184797810 admin can crud product

### PR DESCRIPTION
**Pull request by bencyubahiro77**
#### What does this PR do?
The admin will CRUD product

#### Description of Task to be completed?
the admin will be able to create,read,update and delete a product as a seller does and he can also delete,edit and change availability of product of other sellers

#### How should this be manually tested?
-in terminal add ``npm install``
-add ``.env`` file in your repo and assign the variables as there are in ``.env.example file``
-run in terminal ``npm run migrate:all`` to setup the database
-run in terminal ``npm start`` to start the project
-in your browser add`` http://localhost:<your port>/api-docs`` for documentantion
-login with an account which has role of admin

#### Any background context you want to provide?
na
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184797810

#### Screenshots (if appropriate)
Screenshot 2023-03-27 at 17 43 50

### CODE REVIEW

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by INValentin — CHANGES_REQUESTED** [review]
Hello Ben. Looking through your code changes, it looks likes you just changes to allowed roles to include. But there is also the `isOwner` middleware which will check for the id of the current logged in user, and check if he/she is the seller. Have you tested your implementation, and you're sure this works. 
And you don't seem to have any tests to check your implementation.
If I'm missing something please let me know.

**Review by Zeden12 — APPROVED** [review]
LGTM

**Comment by bencyubahiro77** [comment]
> Hello Ben. Looking through your code changes, it looks likes you just changes to allowed roles to include. But there is also the `isOwner` middleware which will check for the id of the current logged in user, and check if he/she is the seller. Have you tested your implementation, and you're sure this works. And you don't seem to have any tests to check your implementation. If I'm missing something please let me know.

you can check again everything works

**Pull request closed without merging**
