### PR TITLE
#184581357 A user should be able to mark one/all Notification as read

### PR DESCRIPTION
**Pull request by INValentin**
#### What does this PR do?
This PR adds the ability to mark notifications as read, or unread
#### Description of Task to be completed?
A user should be able to mark one/all Notification as read
#### How should this be manually tested?
- run `npm install && npm run migrate:all && npm start`
- Visit `/api-docs` and you should see `notifications` section in the `swagger` documentation -- use that for testing.
#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581357
#### Screenshots (if appropriate)
Screenshot 2023-03-28 at 16 06 52
Screenshot 2023-03-28 at 17 08 51

#### Questions:
n/a

### CODE REVIEW

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
Resolve the unresolved conversation and update README otherwise LGTM

**Comment by INValentin** [comment]
> Resolve the unresolved conversation and update README otherwise LGTM

Actually, I'm unable to resolve that one conversation; since I can't seem to find it anywhere!

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
