### PR TITLE
#184581320 Integrate HoundCi with badge attached to readme

### PR DESCRIPTION
**Pull request by Zeden12**
This is a configuration of HoundCi which will automatically reviews pull requests for style guide violations and other potential issues in the codebase.
HoundCI will  also helps to ensure that code adheres to a consistent style and quality across the codebase, which can improve the readability, maintainability, and overall quality of the code.
And it will allows the tool to provide accurate and useful feedback on pull requests, which can help us to catch potential issues early in the development process.
Here By catching these issues early, teams can save time and effort that would otherwise be spent on debugging and fixing problems later on.

### CODE REVIEW

**Comment by INValentin** [comment]
This looks good to me, and since this will help others check their code before merging pull request it should be merged ASAP!

**Comment by Martha-Iradukunda** [comment]
Hi, well done Earnest. I like the fact that HoundCI will catch issues as a way of debugging the code to save our time. Am looking forward to test it for assurance of our product's quality.

**Comment by Martha-Iradukunda** [comment]
Hi, well done Earnest. I like the fact that HoundCI will catch issues as a way of debugging the code to save our time. Am looking forward to test it for assurance of our product's quality.

**Comment by Patienceineza** [comment]
zidan well done

**Comment by Patienceineza** [comment]
this will help us check the standard of our codes

**Pull request closed without merging**
