### PR TITLE
#184581351 Buyer should be able to view their cart

### PR DESCRIPTION
**Pull request by Zeden12**
#### What does this PR do?

this PR is for buyer to view their cart and admin can be able to view all carts

#### Description of Task to be completed?

this task is to create a route so the current logged in user can view their cart 
-user should be able to view all products in his/her cart

The cart should be retrieved from the buyer's session
The product details should be retrieved from the database for each item in the cart
The cart total should be calculated by summing the prices of the items in the cart

#### How should this be manually tested?

-first clone repo,run npm run migrate:all 
-login and put token in bearer

use this end point /cart with GET to view your cart as a buyer
use also this /cart/all with GET when you logged in as admin to view all carts created by buyers

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184581351

#### Screenshots (if appropriate)

Screen Shot 2023-03-23 at 18 26 43

Screen Shot 2023-03-23 at 18 25 49

Screen Shot 2023-03-23 at 19 39 38

### CODE REVIEW

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by INValentin — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]

**Review by blackd44 — APPROVED** [review]
LG

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
