### PR TITLE
184797811 admin should get all orders

### PR DESCRIPTION
**Pull request by bencyubahiro77**
#### What does this PR do?
This PR Admin should get all orders from all buyers.
#### Description of Task to be completed?
The admin will be able to get all orders made by all buyers and sellers but in general i called them buyers
#### How should this be manually tested?
-in terminal add npm install
-add ``.env`` file in your repo and assign the variables as there are in ``.env.example`` file
-run in terminal ``npm run migrate:all`` to setup the database
-run in terminal ``npm start`` to start the project
-in your browser add ``http://localhost:<your port>/api-docs`` for documentation
-login with an account which has role of admin.
-then with ``GET`` method run ``/checkout/buyer-orders``
-after that you will able to get all orders ,where the order made will be able to be retrieved with the owner details 

#### Any background context you want to provide?
na
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184797811

#### Screenshots (if appropriate)
Screenshot 2023-03-30 at 13 23 34

### CODE REVIEW

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by Habihirwe — APPROVED** [review]
great

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by UmuhireJessie — COMMENTED** [review]
Good job!
Update the readme file and rebase

**Review by UmuhireJessie — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Ensure that all checks are passing

**Pull request closed without merging**
