### PR TITLE
 #184581361 Chat on the App  publicly

### PR DESCRIPTION
**Pull request by edwinnambaje**
#### What does this PR do?

-Adds the chat functionality to the platform

#### Description of Task to be completed?
- Users should be able to chat on the App to ask for some information publicly

#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in terminal `npm run migrate:all` to setup the database
- run in terminal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentation
- in your browser add `http://localhost:<your port>/chat` and login then start chatting

#### Any background context you want to provide?
-Sockets

#### What are the relevant pivotal tracker/Trello stories?
-https://www.pivotaltracker.com/n/projects/2632830/stories/184581361

#### Screenshots (if appropriate)
Screenshot 2023-03-24 at 11 43 53
Screenshot 2023-03-24 at 16 40 18
Screenshot 2023-03-24 at 11 42 37
Screenshot 2023-03-24 at 11 20 41
Screenshot 2023-03-24 at 11 42 46
Screenshot 2023-03-24 at 17 13 08

### CODE REVIEW

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by blackd44 — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by INValentin — APPROVED** [review]

**Review by Habihirwe — APPROVED** [review]
LGMT

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]
I understand that you might have created a UI for demonstration purposes, but please note that you may need to modify it if it needs to be when we get to the front end of the project.

**Pull request merged**
