### PR TITLE
  #184664608 Admin can  create another admin

### PR DESCRIPTION
**Pull request by Patienceineza**
#### What does this PR do?

this PR is for creating admin by another admin

#### How should this be manually tested?

> run `npm run migarte:all`
> then use this path`  users/Create-admin/:email` where email is email of user to be made admin
> then if you are  an admin log in and then create another ADMIN

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker/Trello stories?

  https://www.pivotaltracker.com/story/show/184664608

#### Screenshots (if appropriate)
Screenshot 2023-03-14 at 17 21 18
Screenshot 2023-03-14 at 19 33 15
Screenshot 2023-03-14 at 20 25 14

#### Questions:

n/a

### CODE REVIEW

**Review by INValentin — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Zeden12 — APPROVED** [review]
LGTM

**Comment by Martha-Iradukunda** [comment]
LGTM

**Review by blackd44 — APPROVED** [review]
Looks Good

**Review by UmuhireJessie — APPROVED** [review]
Well done!

**Pull request merged**
