### PR TITLE
remove DS_Strore file

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
fix the bug for pushing DS_Store file

#### Description of Task to be completed?
I managed to remove DS_Store file in the project

#### How should this be manually tested?
in terminal add `npm install`
To run tests in terminal add `npm test`
and then add `.env` in your repo and assign the variables as there are in `.env.example` file

#### Any background context you want to provide?
n/a

#### What are the relevant pivotal tracker/Trello stories?
n/a

#### Screenshots (if appropriate)
n/a

#### Questions:
n/a

### CODE REVIEW

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by INValentin — APPROVED** [review]
LDTM

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by Nkbtemmy — APPROVED** [review]

**Review by SimonImanigirimpuhwe — APPROVED** [review]

**Pull request merged**
