### PR TITLE
#184581317 Configuring connection to postgres database

### PR DESCRIPTION
**Pull request by Patienceineza**
#### What does this PR do?

This PR is for Configuring  The App to use PostgreSQL as DB Engine and Sequelize ORM

####  Description of Task to be completed?

This task is associated with creating a folder and setting your connection to that database in that folder setting models and migration and all other important aspects to the database and its tables 

#### How should this be manually tested?

 This can be tested by 

- Cloning this repo
- Cype `npm install `in your terminal

- Adding the DATABASE_URL in your .env file in this format

-  postgres://username:password@127.0.0.1:port/database_name

#### Any background context you want to provide?

N/a

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184581317

#### Screenshots (if appropriate)

N/a

### CODE REVIEW

**Review by Martha-Iradukunda — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
rename your commit message to `chore(configuration):Configuration of connection to postgres database`

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Pull request merged**
