### PR TITLE
#184581336 Profile Page Setting (GET and PATCH)

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
The PR is for getting and editing the user profile

#### Description of Task to be completed?
the PR has the following endPoints
- GET /users/profile
- PATCH /users/profile

here the user must be logged in so that they get his/her data in the JWT token
- for GET it returns 
```
{
  "username": "string",
  "email": "string",
  "gender": "string",
  "role": "string"
}
```
- for PATCH it returns `token` so that in case the email changes the user get other token
```
{
  "token": "string",
  "username": "string",
  "email": "string",
  "gender": "string",
  "role": "string"
}
```
#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm run migrate:all` to setup the database
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs` for documentantion

#### Any background context you want to provide?
uses `Jwt` library 

#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2632830/stories/184581336

#### Screenshots (if appropriate)
Screen Shot 2023-03-14 at 13 40 21
Screen Shot 2023-03-14 at 13 40 54
Screen Shot 2023-03-14 at 13 42 23

#### Questions:
n/a

### CODE REVIEW

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by bencyubahiro77 — APPROVED** [review]

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Review by UmuhireJessie — APPROVED** [review]
Good work

**Pull request merged**
