### PR TITLE
#184581324 Setting up Swagger Documentation

### PR DESCRIPTION
**Pull request by blackd44**
#### What does this PR do?
setting up swagger documentation

#### Description of Task to be completed?
Task was to set up the swagger documentation in the project
and it has the following endpoints working
- /api-docs

added the following packages
- swagger-jsdoc
- swagger-ui-express

#### How should this be manually tested?
after cloning the repo,
- in terminal add `npm install`
- add `.env` in your repo and assign the variables as there are in `.env.example` file
- run in termainal `npm start` to start the project
- in your browser add `http://localhost:<your port>/api-docs`

#### Any background context you want to provide?
n/a

#### What are the relevant pivotal tracker/Trello stories?
#184581324  (Setup API documentation using swagger)
https://www.pivotaltracker.com/n/projects/2632830/stories/184581324

#### Screenshots (if appropriate)
Screen Shot 2023-03-07 at 14 41 22

#### Questions:
n/a

### CODE REVIEW

**Review by Zeden12 — APPROVED** [review]
LGTM

**Review by edwinnambaje — CHANGES_REQUESTED** [review]
i think you can add  well the respective link to your relevant pivot tracker story

**Review by bencyubahiro77 — APPROVED** [review]

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by edwinnambaje — APPROVED** [review]
LGTM

**Pull request merged**
